### ISSUE TITLE
Slow rendering when changes with 60 rows

### ISSUE THREAD

**Issue by pabloalcaraz** [ant-design/editable-table#4]
I have a Table with 60 Rows and when I change something it renders the whole table, I saw this because takes a lot of time and there is a console.log in index.esm.js line 954.

This is my code 

`<EditableTable
          pagination={{ pageSize: 50, showSizeChanger: false }}
          showAdd
          bordered
          rowKey={(record) => record.dataIndex}
          onAdd={() => {
            onAdd();
          }}
          addText="Nuevo"
          loading={loading}
          columns={columns}
          dataSource={historial}
          onChange={(key, value, record, newDataSource) => {
            onChange(record);
          }}
        />`

The upper component

`<UserTable
                  historial={historial}
                  recompensas={dataRecompensas}                  
                  onChange={(recordChanged) => {
                    //Things                   
                    setHistorial(newHis);
                  }}
                />`

**Comment by lth707** [comment]
Thank you for pointing out the problem, I have fixed it.

**Comment by lth707** [comment]
Thank you for pointing out the problem, I have fixed it.

**Comment by pabloalcaraz** [comment]
Hi,

But the problem of performance is not solved.

I've just tested with only 60 rows, and when you change something it takes time frozen.

Look here, i've just copied your example and added 60 rows.

https://fdo2p.csb.app/
